#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-ordereddict
Version  : 1.1
Release  : 40
URL      : http://pypi.debian.net/ordereddict/ordereddict-1.1.tar.gz
Source0  : http://pypi.debian.net/ordereddict/ordereddict-1.1.tar.gz
Summary  : UNKNOWN
Group    : Development/Tools
License  : MIT
Requires: deprecated-ordereddict-license = %{version}-%{release}
Requires: deprecated-ordereddict-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3

%description
No detailed description available

%package legacypython
Summary: legacypython components for the deprecated-ordereddict package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-ordereddict package.


%package license
Summary: license components for the deprecated-ordereddict package.
Group: Default

%description license
license components for the deprecated-ordereddict package.


%package python
Summary: python components for the deprecated-ordereddict package.
Group: Default

%description python
python components for the deprecated-ordereddict package.


%prep
%setup -q -n ordereddict-1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554324269
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-ordereddict
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-ordereddict/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-ordereddict/LICENSE

%files python
%defattr(-,root,root,-)
